import random
import sqlite3

ADJECTIVES = [
    "bold",
    "brave",
    "bright",
    "calm",
    "clean",
    "cool",
    "crisp",
    "deft",
    "eager",
    "fair",
    "fast",
    "firm",
    "free",
    "fresh",
    "glad",
    "gold",
    "grand",
    "green",
    "keen",
    "kind",
    "light",
    "live",
    "lucky",
    "mild",
    "neat",
    "noble",
    "plain",
    "prime",
    "proud",
    "pure",
    "quick",
    "quiet",
    "rapid",
    "rich",
    "sharp",
    "shy",
    "sleek",
    "slim",
    "smart",
    "smooth",
    "soft",
    "solid",
    "still",
    "strong",
    "sure",
    "sweet",
    "swift",
    "true",
    "warm",
    "wise",
]

NOUNS = [
    "badger",
    "bear",
    "brook",
    "cedar",
    "cloud",
    "coral",
    "crane",
    "creek",
    "crow",
    "dawn",
    "deer",
    "dove",
    "dune",
    "eagle",
    "elm",
    "ember",
    "falcon",
    "fern",
    "finch",
    "flame",
    "flint",
    "fox",
    "frost",
    "grove",
    "hawk",
    "heron",
    "hill",
    "iris",
    "jade",
    "jay",
    "lark",
    "leaf",
    "lion",
    "maple",
    "moon",
    "oak",
    "otter",
    "owl",
    "peak",
    "pine",
    "pond",
    "raven",
    "reef",
    "ridge",
    "river",
    "robin",
    "sage",
    "seal",
    "stone",
    "wolf",
]


def generate_run_name(conn: sqlite3.Connection, max_attempts: int = 100) -> str:
    existing = {row[0] for row in conn.execute("SELECT name FROM runs").fetchall()}
    for _ in range(max_attempts):
        name = f"{random.choice(ADJECTIVES)}-{random.choice(NOUNS)}"
        if name not in existing:
            return name
    raise RuntimeError(
        f"Could not generate a unique run name after {max_attempts} attempts. "
        f"Consider providing an explicit run_name."
    )
